name: release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make && tar -czvf hello.tar.gz hello

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: hello.tar.gz
          path: ./hello.tar.gz

  gensha:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate
        run: |
          echo ${{github.sha}} > release.txt
          git log --oneline --format="* %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >release.log

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            ./release.txt
            ./release.log

  release:
    runs-on: ubuntu-22.04
    needs: [build, gensha]
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: hello.tar.gz

      - name: Download sha
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./release.log
          files: |
            release.txt
            hello.tar.gz
