name: release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make && tar -czvf hello.tar.gz hello

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: hello.tar.gz
          path: ./hello.tar.gz

  gensha:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: echo ${{github.sha}} > release.txt

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: release.txt
          path: ./release.txt

  release:
    runs-on: ubuntu-22.04
    needs: [build, gensha]
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: hello.tar.gz

      - name: Download sha
        uses: actions/download-artifact@v3
        with:
          name: release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release.txt
            hello.tar.gz
